"""empty message

Revision ID: 6aef7a9090b7
Revises: 89a61e178cfe
Create Date: 2021-07-04 14:03:43.668862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aef7a9090b7'
down_revision = '89a61e178cfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_trip_id_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_stop_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'trip_id')
    op.drop_column('comments', 'stop_id')
    op.drop_column('comments', 'body')
    op.drop_column('comments', 'title')
    op.drop_constraint('items_owner_id_fkey', 'items', type_='foreignkey')
    op.drop_column('items', 'notes')
    op.drop_column('items', 'owner_id')
    op.drop_column('items', 'title')
    op.drop_constraint('list_types_name_key', 'list_types', type_='unique')
    op.drop_column('list_types', 'description')
    op.drop_column('list_types', 'name')
    op.drop_column('list_types', 'color')
    op.drop_column('lists', 'name')
    op.drop_column('lists', 'notes')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_column('users', 'about')
    op.drop_column('users', 'on_trip')
    op.drop_column('users', 'email')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('on_trip', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('about', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.add_column('lists', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('lists', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('list_types', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('list_types', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('list_types', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_unique_constraint('list_types_name_key', 'list_types', ['name'])
    op.add_column('items', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('items', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('items', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key('items_owner_id_fkey', 'items', 'users', ['owner_id'], ['id'])
    op.add_column('comments', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('comments', sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('comments', sa.Column('stop_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('trip_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_stop_id_fkey', 'comments', 'stops', ['stop_id'], ['id'])
    op.create_foreign_key('comments_trip_id_fkey', 'comments', 'trips', ['trip_id'], ['id'])
    # ### end Alembic commands ###
