"""empty message

Revision ID: e10e69d2d57b
Revises: eb7aeee65b39
Create Date: 2021-07-09 13:42:16.337782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e10e69d2d57b'
down_revision = 'eb7aeee65b39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'itemName')
    op.drop_column('items', 'itemNotes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('itemNotes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('itemName', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
