"""empty message

Revision ID: 2a2af9ad03f2
Revises: 8e309678c4ce
Create Date: 2021-07-08 13:50:26.282953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a2af9ad03f2'
down_revision = '8e309678c4ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
