"""empty message

Revision ID: 960ed484c59f
Revises: ad5e1f84921a
Create Date: 2021-07-10 18:06:30.280986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960ed484c59f'
down_revision = 'ad5e1f84921a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
