"""empty message

Revision ID: da14838a8b0c
Revises: 22e6a2935e3d
Create Date: 2021-07-08 21:27:56.189350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da14838a8b0c'
down_revision = '22e6a2935e3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
