"""empty message

Revision ID: 2bc69ef4ea52
Revises: 218199c46630
Create Date: 2021-07-08 13:58:04.074037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bc69ef4ea52'
down_revision = '218199c46630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
