"""empty message

Revision ID: 218199c46630
Revises: 8a521173808a
Create Date: 2021-07-08 13:55:39.451007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218199c46630'
down_revision = '8a521173808a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'pedestrian')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('pedestrian', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
