"""empty message

Revision ID: ac45a7c812d2
Revises: 960ed484c59f
Create Date: 2021-07-10 18:16:16.973829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac45a7c812d2'
down_revision = '960ed484c59f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
