"""empty message

Revision ID: a5dd07d2e9ae
Revises: 8546e8c7954d
Create Date: 2021-07-08 14:04:10.893238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5dd07d2e9ae'
down_revision = '8546e8c7954d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
