"""empty message

Revision ID: 56ecbf48652c
Revises: d4b6e5632738
Create Date: 2021-07-02 16:11:45.262987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56ecbf48652c'
down_revision = 'd4b6e5632738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('comments_stop_id_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_photo_id_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_trip_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'trip_id')
    op.drop_column('comments', 'stop_id')
    op.drop_column('comments', 'title')
    op.drop_column('comments', 'body')
    op.drop_column('comments', 'photo_id')
    op.drop_constraint('list_types_name_key', 'list_types', type_='unique')
    op.drop_column('list_types', 'description')
    op.drop_column('list_types', 'color')
    op.drop_column('list_types', 'name')
    op.drop_constraint('lists_list_type_fkey', 'lists', type_='foreignkey')
    op.drop_column('lists', 'notes')
    op.drop_column('lists', 'list_type')
    op.drop_column('lists', 'name')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_column('users', 'about')
    op.drop_column('users', 'on_trip')
    op.drop_column('users', 'username')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('on_trip', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('about', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.add_column('lists', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('lists', sa.Column('list_type', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('lists', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key('lists_list_type_fkey', 'lists', 'list_types', ['list_type'], ['id'])
    op.add_column('list_types', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('list_types', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('list_types', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_unique_constraint('list_types_name_key', 'list_types', ['name'])
    op.add_column('comments', sa.Column('photo_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('comments', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('comments', sa.Column('stop_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('trip_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_trip_id_fkey', 'comments', 'trips', ['trip_id'], ['id'])
    op.create_foreign_key('comments_photo_id_fkey', 'comments', 'photos', ['photo_id'], ['id'])
    op.create_foreign_key('comments_stop_id_fkey', 'comments', 'stops', ['stop_id'], ['id'])
    op.drop_table('items')
    # ### end Alembic commands ###
