"""empty message

Revision ID: 8fca761b954c
Revises: ee2ca6454b91
Create Date: 2021-07-08 21:29:27.371592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fca761b954c'
down_revision = 'ee2ca6454b91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
