"""empty message

Revision ID: 8a521173808a
Revises: 2a2af9ad03f2
Create Date: 2021-07-08 13:54:40.303346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a521173808a'
down_revision = '2a2af9ad03f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('pedestrian', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'pedestrian')
    # ### end Alembic commands ###
