"""empty message

Revision ID: ee2ca6454b91
Revises: da14838a8b0c
Create Date: 2021-07-08 21:29:16.765473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee2ca6454b91'
down_revision = 'da14838a8b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
