"""empty message

Revision ID: 8546e8c7954d
Revises: 2bc69ef4ea52
Create Date: 2021-07-08 13:59:01.298250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8546e8c7954d'
down_revision = '2bc69ef4ea52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('listName', sa.String(length=50), nullable=False))
    op.add_column('items', sa.Column('listNotes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'listNotes')
    op.drop_column('items', 'listName')
    # ### end Alembic commands ###
