"""empty message

Revision ID: 22e6a2935e3d
Revises: 0fdea9792074
Create Date: 2021-07-08 21:14:54.697763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e6a2935e3d'
down_revision = '0fdea9792074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
