name: Python application

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        HEROKU_API_KEY: ${{ secrets.9d969c52-060d-4312-9e1d-bcf28e562f89 }}
    steps:
    - uses: actions/checkout@v2
    - name: Login to Heroku Container registry
      run: heroku container:login
    - name: Build and push
      run: heroku container:push -a dont-forget-the-gas web
    - name: Release
      run: heroku container:release -a dont-forget-the-gas web
      
