name: Python application

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        HEROKU_API_KEY: ${{ secrets.d6e19ee7-97f5-4e44-ab05-6de1460b829e }}
    steps:
    - uses: actions/checkout@v2
    - name: Login to Heroku Container registry
      run: heroku container:login
    - name: Build and push
      run: heroku container:push -a dont-forget-the-gas web
    - name: Release
      run: heroku container:release -a dont-forget-the-gas web
      
